name: lr1600-cad
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cadquery
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pyyaml
  - ezdxf
  - shapely
  - svgwrite
  - pytest
  - pip
  - pip:
      - ocp-vscode==4.0.1
